---
kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: golang:1.13
  commands:
  - make cmd/agent/agent
  - make cmd/api/api
  - make cmd/ui/ui
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
    GOPROXY: https://proxy.golang.org

- name: dart
  pull: always
  image: google/dart:2.3
  commands:
  - cd ui
  - pub get --no-precompile
  - pub global activate webdev
  - ~/.pub-cache/bin/webdev build
  - rm -rf build/packages
  - cp -r build/ ../cmd/ui/assets/

- name: docker-api
  image: plugins/docker
  settings:
    context: ./cmd/api/
    dockerfile: cmd/api/Dockerfile
    password:
      from_secret: quay_password
    registry: quay.io
    repo: quay.io/signalcd/api
    username:
      from_secret: quay_username
  when:
    branch:
    - master
    event:
    - push

- name: docker-agent
  image: plugins/docker
  settings:
    context: ./cmd/agent/
    dockerfile: cmd/agent/Dockerfile
    password:
      from_secret: quay_password
    registry: quay.io
    repo: quay.io/signalcd/agent
    username:
      from_secret: quay_username
  when:
    branch:
    - master
    event:
    - push

- name: docker-ui
  image: plugins/docker
  settings:
    context: ./cmd/ui/
    dockerfile: cmd/ui/Dockerfile
    password:
      from_secret: quay_password
    registry: quay.io
    repo: quay.io/signalcd/ui
    username:
      from_secret: quay_username
  when:
    branch:
    - master
    event:
    - push

---
kind: pipeline
name: test

platform:
  os: linux
  arch: amd64

steps:
- name: test-unit
  pull: always
  image: golang:1.13
  commands:
  - make test-unit
  environment:
    CGO_ENABLED: 1
    GO111MODULE: on
    GOPROXY: https://proxy.golang.org

---
kind: pipeline
name: code-generation

platform:
  os: linux
  arch: amd64

steps:
- name: goswagger-apiv1
  image: quay.io/goswagger/swagger:v0.19.0
  commands:
  - make api/v1/client api/v1/models api/v1/restapi
  - git diff --exit-code
  environment:
    GOSWAGGER: /usr/bin/swagger

- name: grpc
  image: grpc/go
  commands:
  - make signalcd/proto/agent.pb.go
  - git diff --exit-code

---
kind: pipeline
name: checks

platform:
  os: linux
  arch: amd64

steps:
- name: build-kubernetes-status
  pull: always
  image: golang:1.13
  commands:
  - make cmd/checks/kubernetes-status/kubernetes-status
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
    GOPROXY: https://proxy.golang.org

- name: docker-kubernetes-status
  image: plugins/docker
  settings:
    context: cmd/checks/kubernetes-status
    dockerfile: cmd/checks/kubernetes-status/Dockerfile
    password:
      from_secret: quay_password
    registry: quay.io
    repo: quay.io/signalcd/kubernetes-status
    username:
      from_secret: quay_username
  when:
    branch:
    - master
    event:
    - push

---
kind: pipeline
name: plugins

platform:
  os: linux
  arch: amd64

steps:
- name: build-drone
  pull: always
  image: golang:1.13
  commands:
  - make cmd/plugins/drone/drone
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
    GOPROXY: https://proxy.golang.org

- name: docker-drone
  image: plugins/docker
  settings:
    context: cmd/plugins/drone
    dockerfile: cmd/plugins/drone/Dockerfile
    password:
      from_secret: quay_password
    registry: quay.io
    repo: quay.io/signalcd/drone
    username:
      from_secret: quay_username
  when:
    branch:
    - master
    event:
    - push

---
kind: pipeline
name: examples

platform:
  os: linux
  arch: amd64

steps:
- name: docker-examples-cheese0
  image: plugins/docker
  settings:
    context: examples/cheese0
    dockerfile: examples/cheese0/Dockerfile
    password:
      from_secret: quay_password
    registry: quay.io
    repo: quay.io/signalcd/examples
    tags:
    - cheese0
    username:
      from_secret: quay_username
  when:
    branch:
    - master
    event:
    - push

- name: docker-examples-cheese1
  image: plugins/docker
  settings:
    context: examples/cheese1
    dockerfile: examples/cheese1/Dockerfile
    password:
      from_secret: quay_password
    registry: quay.io
    repo: quay.io/signalcd/examples
    tags:
    - cheese1
    username:
      from_secret: quay_username
  when:
    branch:
    - master
    event:
    - push

- name: docker-examples-cheese2
  image: plugins/docker
  settings:
    context: examples/cheese2
    dockerfile: examples/cheese2/Dockerfile
    password:
      from_secret: quay_password
    registry: quay.io
    repo: quay.io/signalcd/examples
    tags:
    - cheese2
    username:
      from_secret: quay_username
  when:
    branch:
    - master
    event:
    - push

...
