---
kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: golang:1.13
  commands:
  - make cmd/agent/agent
  - make cmd/api/api
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
    GOPROXY: https://proxy.golang.org

- name: dart
  pull: always
  image: google/dart:2.3
  commands:
  - cd ui
  - pub get --no-precompile
  - pub global activate webdev
  - ~/.pub-cache/bin/webdev build
  - rm -rf build/packages
  - cp -r build/ ../cmd/api/assets/

- name: docker-api
  image: plugins/docker
  settings:
    context: ./cmd/api/
    dockerfile: cmd/api/Dockerfile
    password:
      from_secret: quay_password
    registry: quay.io
    repo: quay.io/signalcd/api
    username:
      from_secret: quay_username
  when:
    branch:
    - master
    event:
    - push

- name: docker-agent
  image: plugins/docker
  settings:
    context: ./cmd/agent/
    dockerfile: cmd/agent/Dockerfile
    password:
      from_secret: quay_password
    registry: quay.io
    repo: quay.io/signalcd/agent
    username:
      from_secret: quay_username
  when:
    branch:
    - master
    event:
    - push

---
kind: pipeline
name: test

platform:
  os: linux
  arch: amd64

steps:
- name: test-unit
  pull: always
  image: golang:1.13
  commands:
  - make test-unit
  environment:
    CGO_ENABLED: 1
    GO111MODULE: on
    GOPROXY: https://proxy.golang.org

---
kind: pipeline
name: code-generation

platform:
  os: linux
  arch: amd64

steps:
- name: grpc
  image: golang:1.13-alpine
  commands:
  - apk add -U git make protobuf protoc
  - go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
  - go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger
  - go get -u github.com/golang/protobuf/protoc-gen-go
  - make signalcd/proto --always-make
  - git diff --exit-code signalcd/proto
  environment:
    GOPROXY: https://proxy.golang.org

- name: dart-swagger
  image: openapitools/openapi-generator-cli:v4.2.3
  commands:
  - apk add -U git make
  - make ui/lib/src/api --always-make
  - git diff --exit-code ui/lib/src/api
  environment:
    SWAGGER: /usr/local/bin/docker-entrypoint.sh

---
kind: pipeline
name: checks

platform:
  os: linux
  arch: amd64

steps:
- name: build-kubernetes-status
  pull: always
  image: golang:1.13
  commands:
  - make cmd/checks/kubernetes-status/kubernetes-status
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
    GOPROXY: https://proxy.golang.org

- name: docker-kubernetes-status
  image: plugins/docker
  settings:
    context: cmd/checks/kubernetes-status
    dockerfile: cmd/checks/kubernetes-status/Dockerfile
    password:
      from_secret: quay_password
    registry: quay.io
    repo: quay.io/signalcd/check-kubernetes-status
    username:
      from_secret: quay_username
  when:
    branch:
    - master
    event:
    - push

- name: build-http
  pull: always
  image: golang:1.13
  commands:
  - make cmd/checks/http/http
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
    GOPROXY: https://proxy.golang.org

- name: docker-http
  image: plugins/docker
  settings:
    context: cmd/checks/http
    dockerfile: cmd/checks/http/Dockerfile
    password:
      from_secret: quay_password
    registry: quay.io
    repo: quay.io/signalcd/check-http
    username:
      from_secret: quay_username
  when:
    branch:
    - master
    event:
    - push

---
kind: pipeline
name: plugins

platform:
  os: linux
  arch: amd64

steps:
- name: build-drone
  pull: always
  image: golang:1.13
  commands:
  - make cmd/plugins/drone/drone
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
    GOPROXY: https://proxy.golang.org

- name: docker-drone
  image: plugins/docker
  settings:
    context: cmd/plugins/drone
    dockerfile: cmd/plugins/drone/Dockerfile
    password:
      from_secret: quay_password
    registry: quay.io
    repo: quay.io/signalcd/drone
    username:
      from_secret: quay_username
  when:
    branch:
    - master
    event:
    - push

---
kind: pipeline
name: examples

platform:
  os: linux
  arch: amd64

steps:
- name: docker-examples-cheese0
  image: plugins/docker
  settings:
    context: examples/cheese0
    dockerfile: examples/cheese0/Dockerfile
    password:
      from_secret: quay_password
    registry: quay.io
    repo: quay.io/signalcd/examples
    tags:
    - cheese0
    username:
      from_secret: quay_username
  when:
    branch:
    - master
    event:
    - push

- name: docker-examples-cheese1
  image: plugins/docker
  settings:
    context: examples/cheese1
    dockerfile: examples/cheese1/Dockerfile
    password:
      from_secret: quay_password
    registry: quay.io
    repo: quay.io/signalcd/examples
    tags:
    - cheese1
    username:
      from_secret: quay_username
  when:
    branch:
    - master
    event:
    - push

- name: docker-examples-cheese2
  image: plugins/docker
  settings:
    context: examples/cheese2
    dockerfile: examples/cheese2/Dockerfile
    password:
      from_secret: quay_password
    registry: quay.io
    repo: quay.io/signalcd/examples
    tags:
    - cheese2
    username:
      from_secret: quay_username
  when:
    branch:
    - master
    event:
    - push

...
