openapi: "3.0.0"
info:
  version: 0.0.1
  title: CD OpenAPI Spec
  description: OpenAPI 3.0 specification for CD
servers:
  - url: http://localhost:6660/v1
paths:
  /pipeline:
    get:
      description: |
        Returns the current executed pipeline
      operationId: pipelineCurrent
      responses:
        '200':
          description: pipeline response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/pipeline'
        '404':
          description: current exexcuted pipeline could not be found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/pipeline'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
    patch:
      description: |
        updates the current pipeline
      operationId: updateCurrentPipeline
      responses:
        '200':
          description: pipeline response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/pipeline'
        '404':
          description: current exexcuted pipeline could not be found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/pipeline'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
  /pipelines:
    get:
      description: returns a list of all pipelines
      operationId: pipelines
      responses:
        '200':
          description: list of pipelines response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/pipeline'
        '404':
          description: current exexcuted pipeline could not be found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/pipeline'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
  /pipelines/{id}:
    get:
      description: returns a pipeline by id
      operationId: pipeline
      parameters:
        - name: id
          in: path
          description: ID of pipeline to fetch
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: pipeline response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/pipeline'
        '404':
          description: current exexcuted pipeline could not be found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/pipeline'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
  /pipelines/status:
    get:
      description: returns a pipeline by id
      operationId: pipelineAgents
      parameters:
        - name: id
          in: path
          description: ID of pipeline to fetch
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: pipeline response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/pipeline'
        '404':
          description: current exexcuted pipeline could not be found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/pipeline'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
    post:
      description: returns a pipeline by id
      operationId: updatePipelineAgents
      parameters:
        - in: query
          name: updateStatusOptions
          content:
            application/json:
              schema:
                type: object
                properties:
                  agent:
                    type: string
                  healthy:
                    type: boolean
      responses:
        '200':
          description: pipeline response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/pipeline'
        '404':
          description: current exexcuted pipeline could not be found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/pipeline'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  schemas:
    pipeline:
      required:
        - name
      properties:
        id:
          type: string
          format: uuid
        steps:
          $ref: '#/components/schemas/step'
        checks:
          $ref: '#/components/schemas/check'
    step:
      required:
        - name
        - image
      properties:
        name:
          type: string
        image:
          type: string
        commands:
          type: array
          items:
            type: string
    check:
      required:
        - name
        - image
        - duration
      properties:
        name:
          type: string
        image:
          type: string
        duration:
          type: number
        environment:
          type: object
          additionalProperties:
            type: object
            properties:
              key:
                type: string
              value:
                type: string
    error:
      type: object
      required:
        - message
      properties:
        message:
          type: string