name: ui
description: A web app that uses AngularDart
version: 0.0.1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  angular: ^5.3.0

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.6.1
  build_test: ^0.10.7
  build_web_compilers: ^2.0.0
  test: ^1.3.0
