openapi: 3.0.1
info:
  title: SignalCD
  version: 0.0.0
servers:
  - url: /api/v1
paths:
  /deployments:
    get:
      summary: List Deployments
      operationId: ListDeployments
      tags:
        - deployment
      responses:
        '200':
          description: List of Deployments
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Deployments"
  /deployments/current:
    get:
      summary: Get the current Deployment
      operationId: GetCurrentDeployment
      tags:
        - deployment
      responses:
        '200':
          description: Get the current Deployment
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Deployment"
    post:
      summary: Set the current Deployment
      operationId: SetCurrentDeployment
      tags:
        - deployment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SetCurrentDeployment'
      responses:
        '200':
          description: Current deployment was successfully set.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Deployment"
  /deployments/{id}/status:
    patch:
      summary: Update parts of the Status of a Deployment
      operationId: UpdateDeploymentStatus
      tags:
        - deployment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeploymentStatusUpdate'
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Status update successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Deployment"
  /pipelines:
    get:
      summary: List of Pipelines.
      operationId: ListPipelines
      tags:
        - pipeline
      responses:
        '200':
          description: List of Pipelines.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pipelines'
    post:
      summary: Create a new Pipeline.
      operationId: CreatePipeline
      tags:
        - pipeline
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pipeline'
      responses:
        '200':
          description: The created Pipeline.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pipeline'
  /pipelines/{id}:
    get:
      summary: Get Pipeline by its ID
      operationId: GetPipeline
      tags:
        - pipeline
      parameters:
        - name: id
          in: path
          description: Pipeline ID (UUID)
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: A Pipeline
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pipeline'
components:
  schemas:
    Deployment:
      type: object
      required:
        - number
      properties:
        number:
          type: integer
          format: int64
        created:
          type: string
          format: 'date-time'
        pipeline:
          $ref: '#/components/schemas/Pipeline'
        status:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/DeploymentStatus'
    Deployments:
      type: array
      items:
        $ref: "#/components/schemas/Deployment"
    SetCurrentDeployment:
      type: object
      required:
        - pipelineID
      properties:
        pipelineID:
          type: string
          format: uuid
    DeploymentStatus:
      type: object
      required:
        - steps
      properties:
        steps:
          type: array
          items:
            $ref: '#/components/schemas/DeploymentStepStatus'
    DeploymentStepStatus:
      type: object
      required:
        - phase
        - started
      properties:
        phase:
          type: string
        started:
          type: string
          format: 'date-time'
        stopped:
          type: string
          format: 'date-time'
    DeploymentStatusUpdate:
      type: object
      required:
        - agent
        - step
      properties:
        agent:
          type: string
        step:
          type: integer
          format: int64
        phase:
          type: string
          enum: ['unknown', 'success', 'failure', 'progress', 'pending', 'killed']
    Pipeline:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        created:
          type: string
          format: 'date-time'
        steps:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              image:
                type: string
              imagePullSecrets:
                type: array
                items:
                  type: string
              commands:
                type: array
                items:
                  type: string
    Pipelines:
      type: array
      items:
        $ref: '#/components/schemas/Pipeline'
